const familyTapple = [
    {letter: "A", items: [
        "albert",
        "anthony",
        "anita",
        "annalia",
        "amy",
        "alina",
        "adamo",
        "alec",
        "andre",
        "angel",
        "ana",
        "alex",
        "amner",
        "aury",
        "avy",
    ]},
    {letter: "B", items: [
        "brutus",
        "byron",
        "bryan",
    ]},
    {letter: "C", items: [
        "cindy",
        "cynthia",
        "camila",
        "christopher",
        "camille",
        "carlos",
        "connie",
    ]},
    {letter: "D", items: [
        "david",
        "dany",
        "danny",
        "dani",
        "donald",
        "deklan",
        "dennis",
        "dylan",
        "derek",
        "dolly",
    ]},
    {letter: "E", items: [
        "emilie",
        "eva",
        "emilio",
        "enzo",
        "emerson",
        "eli",
        "emma",
        "eve",
    ]},
    {letter: "F", items: [
        "flynn",
        "francis",
    ]},
    {letter: "G", items: [
        "giggi",
        "gabriel",
    ]},
    {letter: "H", items: [
        "helen",
        "humberto",
    ]},
    {letter: "I", items: [
        "imani",
    ]},
    {letter: "J", items: [
        "jordy",
        "jj",
        "jonathan",
        "jexie",
        "julian",
        "john-andre",
        "jacynte",
        "jocelyne",
        "jade",
        "jordan",
        "jeannie",
        "javier",
    ]},
    {letter: "K", items: [
        "keano",
        "kevin",
        "kylo",
    ]},
    {letter: "L", items: [
        "lianna",
        "luciano",
        "lisa",
        "lydia",
        "louiselle",
        "laura",
        "lincoln",
        "louise",
        "line",
        "linda",
        "luca",
        "lesly",
    ]},
    {letter: "M", items: [
        "montserrat",
        "megan",
        "mark",
        "marc",
        "magda",
        "marcel",
        "marie",
        "madeleine",
        "maddy",
        "melanie",
        "magenta",
        "myllia",
        "matthew",
        "maxime",
        "martine",
        "marie-chantale",
        "maria",
        "marisol",
        "maritza",
    ]},
    {letter: "N", items: [
        "natasha",
        "nathan",
        "nathalie",
        "nicole",
    ]},
    {letter: "O", items: [
        "oliver",
        "olivia",
        "oceanne",
        "olivier",
        "oscar",
    ]},
    {letter: "P", items: [
        "pocahontas",
        "puchy",
        "poochy",
        "pierre",
    ]},
    {letter: "Q", items: [
        
    ]},
    {letter: "R", items: [
        "raphael",
        "ricky",
        "roxane",
        "robert",
        "richard",
    ]},
    {letter: "S", items: [
        "susan",
        "sonia",
        "serena",
        "sofia",
        "stoucy",
        "sabrina",
        "stephen",
        "sylvain",
        "sebastien",
        "simon",
        "stephane",
    ]},
    {letter: "T", items: [
        "tony",
        "tom",
        "tito",
        "tanya",
        "teresse",
    ]},
    {letter: "U", items: [
        
    ]},
    {letter: "V", items: [
        "victoria",
        "valerie",
        "vincent",
    ]},
    {letter: "W", items: [
        "william",
        "willy",
        "woody",
    ]},
    {letter: "X", items: [
        "xavier",
    ]},
    {letter: "Y", items: [
        "yayo",
        "yaya",
        "yan",
        "yves",
    ]},
    {letter: "Z", items: [
        "zachary",
        "zack",
    ]},
]