const rupaulTapple = [
    {letter: "A", items: [
       "a'keria c davenport",
"a'keria c. davenport",
"acid betty",
"adore delano",
"adriana",
"aiden zhane",
"aimee yonce shennel",
"aja",
"akashia",
"akeria c davenport",
"akeria c. davenport",
"alaska",
"alexis mateo",
"alexis michelle",
"alisa summers",
"alyssa edwards",
"alyssa hunter",
"amanda tori meating",
"amethyst",
"anastarzia anaquway",
"anetra",
"angeria",
"angeria paris vanmicheals",
"april carrion",
"april carrión",
"aquaria",
"ariel versace",
"asia o hara",
"asia o'hara",
"asia ohara",
"aura mayari",
"aurora matrix", 
    ]},
    {letter: "B", items: [
        "boa",
"bebe zahara benet",
"ben de la creme",
"ben dela creme",
"bendelacreme",
"beth",
"bianca del rio",
"blair saint clair",
"blair st clair",
"blair st. clair",
"bob the drag queen",
"bombae",
"bosco",
"brita",
"brooke lynn hytes",
    ]},
    {letter: "C", items: [
        "carmen carrera",
"chad michaels",
"charlie hides",
"chelazon leroux",
"chi chi devayne",
"coco montrese",
"courtney act",
"crystal methyd",
"cynthia lee fontaine",
"cynthia lee fontaine",
    ]},
    {letter: "D", items: [
        "dahlia sin",
"darienne lake",
"dawn",
"dax exclamationpoint",
"dax!",
"daya betty",
"deja skye",
"delta work",
"denali",
"denim",
"derrick barry",
"detox",
"dida ritz",
"dusty ray bottoms",
    ]},
    {letter: "E", items: [
        "elliott with 2 ts",
"elliott with two ts",
"eureka",
"eureka",
"eve",
    ]},
    {letter: "F", items: [
        "farrah moan",
"fiercalicious",
    ]},
    {letter: "G", items: [
        "geneva karr",
"gia gunn",
"gia metric",
"gigi goode",
"ginger minj",
"girlfriend experience",
"gisele lullaby",
"gisèle lullaby",
"gottmik",
    ]},
    {letter: "H", items: [
        "halal bae",
"heidi n closet",
"hershii liqcour jete",
"hershii liqcour jeté",
"hershii liqcour-jete",
"hershii liqcour-jeté",
"honey davenport",
"honey mahogany",
    ]},
    {letter: "I", items: [
        "icesis couture",
"ilona verley",
"india ferrah",
"irene dubois",
"irma gerd",
"ivy winters",
    ]},
    {letter: "J", items: [
        "jackie cox",
"jada shada hudson",
"jade",
"jade jolie",
"jaida essence hall",
"jaidynn diore fierce",
"jan",
"jasmine kennedie",
"jasmine masters",
"jax",
"jaymes mansfield",
"jessica wild",
"jiggly caliente",
"jimbo",
"jinkx monsoon",
"joey jay",
"jorgeous",
"joslyn fox",
"juice boxx",
"jujubee",
"june jambalaya",
    ]},
    {letter: "K", items: [
        "kahanna montrese",
"kahmora hall",
"kalorie karbdashian williams",
"kameron michaels",
"kandy ho",
"kandy muse",
"kaos",
"kasha davis",
"katya",
"kelly mantle",
"kendall gender",
"kennedy davenport",
"kenya michaels",
"kerri colby",
"kiara",
"kiki coe",
"kim chi",
"kimmy couture",
"kimora amour",
"kimora blac",
"kitten kaboodle",
"kornbread the snack jeté",
"kornbread jete",
"kornbread jeté",
"kylie sonique love",
"kyne",
    ]},
    {letter: "L", items: [
        "lala ri",
"la la ri",
"lady boom boom",
"lady camden",
"laganja estranja",
"laila mcqueen",
"lashauwn beyond",
"latrice royale",
"lemon",
"lineysha sparx",
"loosey laduca",
"luna dubois",
"luxx noir london",
    ]},
    {letter: "M", items: [
        "madame laqueer",
"maddy morphosis",
"magnolia crawford",
"malaysia babydoll foxx",
"manila luzon",
"marcia marcia marcia",
"mariah",
"max",
"mayhem miller",
"megami",
"melinda verga",
"mercedes iman diamond",
"mhi ya iman le paige",
"mhi ya iman le'paige",
"mhi ya iman lepaige",
"mhi'ya iman la paige",
"mhi'ya iman le'paige",
"mhi'ya iman lepaige",
"mhiya iman la paige",
"mhiya iman le'paige",
"mhiya iman lepaige",
"milan",
"milk",
"mimi imfurst",
"mirage",
"miss fame",
"miss fiercalicious",
"miss moco",
"miss moço",
"miss vanjie",
"mistress isabelle brooks",
"miz cracker",
"mo heart",
"monet x change",
"monica beverly hillz",
"monique heart",
"monét x change",
"morgan mcmichaels",
"morphine love dion",
"mrs. kasha davis",
"ms moco",
"ms moço",
"ms vanjie",
"mystique",
"mystique summers madison",
    ]},
    {letter: "N", items: [
        "naomi smalls",
"naysha lopez",
"nearah nuff",
"nicky doll",
"nicole paige brooks",
"nina bo nina brown",
"nina bo'nina brown",
"nina bonina brown",
"nina flowers",
"nina west",
"nymphia wind",
    ]},
    {letter: "O", items: [
        "oceana aqua black",
"oceane aqua-black",
"océane aqua black",
"océane aqua-black",
"olivia lux",
"ongina",
"orion story",
    ]},
    {letter: "P", items: [
        "pandora boxx",
"pearl",
"penny tration",
"peppermint",
"phi phi o hara",
"phi phi o'hara",
"phi phi ohara",
"phoenix",
"plane jane",
"plasma",
"plastique tiara",
"porkchop",
"princess",
"princess poppy",
"priyanka",
"pythia",
    ]},
    {letter: "Q", items: [
        "q",
    ]},
    {letter: "R", items: [
        "ra'jah o hara",
"ra'jah o'hara",
"ra'jah ohara",
"raja",
"rajah o hara",
"rajah o'hara",
"rajah ohara",
"raven",
"rebecca glasscock",
"rita baga",
"robbie turner",
"robin fierce",
"rock m sakura",
"rock m. sakura",
"rose",
"rosé",
"roxxxy andrews",
    ]},
    {letter: "S", items: [
        "sahara davenport",
"salina estitties",
"sapphira cristal",
"sapphira cristál",
"sasha belle",
"sasha colby",
"sasha velour",
"scarlet envy",
"scarlett bobo",
"serena chacha",
"shangela",
"shangela",
"shangela laquifa wadley",
"shannel",
"sharon needles",
"shea coulee",
"shea couleé",
"sherry pie",
"shuga cain",
"silky nutmeg ganache",
"sisi superstar",
"soju",
"sonique",
"spice",
"stacy layne matthews",
"stephanie prince",
"sugar",
"suki doll",
"symone",
"synthia kiss",
    ]},
    {letter: "T", items: [
        "tamisha iman",
"tammie brown",
"tatianna",
"tempest dujour",
"the girlfriend experience",
"the princess",
"the vixen",
"thorgy thor",
"tina burner",
"trinity k bonet",
"trinity k. bonet",
"trinity taylor",
"trinity the tuck",
"trixie mattel",
"tynomi banks",
"tyra sanchez",
    ]},
    {letter: "U", items: [
        "utica",
"utica queen",
    ]},
    {letter: "V", items: [
        "valentina",
"vanessa vanjie mateo",
"vanessa vanjie mateo",
"vanjie",
"venus",
"venus d-lite",
"victoria parker",
"violet chachki",
"vivacious",
"vivian vanderpuss",
"vivienne pinay",
"vixen",
    ]},
    {letter: "W", items: [
        "widow von du",
"widow von'du",
"widow vondu",
"willam",
"willow pill",
    ]},
    {letter: "X", items: [
        "xunami muse",
    ]},
    {letter: "Y", items: [
        "yara sofia",
"yuhua hamasaki",
"yvie oddly",
    ]},
    {letter: "Z", items: [
        
    ]},
]